<?php

/**
 * Implementation of hook_menu
 */
function sample_data_menu() {
  $items = array();
  
  $items["admin/config/sample-data"] = array(
    "title" => "Sample Data",
    "description" => "Load sample data into FlightPath's database.",
    "page_callback" => "fp_render_form",
    "page_arguments" => array("sample_data_install_form"),
    "access_arguments" => array("administer_sample_data"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "menu_links" => array(         
        0 => array(
          "text" => "Back to main menu",
          "path" => "admin-tools/admin",
        ),
      ),
    ),    
    "type" => MENU_TYPE_NORMAL_ITEM,
    "tab_parent" => "admin-tools/admin",    
  );         
 
  
  return $items;
}

function sample_data_perm() {
  return array("administer_sample_data" => array(
    "title" => t("Administer sample data"),
    "description" => t("Allows for sample data to be installed, DELETING existing data!  Only administrators
                        should have this powerful permission."),
  ));
}

function sample_data_install_form() {
  $form = array();

  $form["mark" . $m++] = array(
    "value" => "<p>" . t("This will install sample data into your database, for courses, groups, and degrees.
                <b>IT WILL OVERWRITE OR ERASE</b> existing data!  So please, back up your database before
                proceeding.") . "</p>",
  );
  
  $form["passcode"] = array(
    "type" => "textfield",
    "label" => t("Are you sure you want to install sample data?"),
    "description" => "Enter YES (all caps) to proceed.",
    
  );  
  
  $form["submit_btn"] = array(
    "type" => "submit",
    "value" => t("Submit"),
    "suffix" => "<p>" . t("Press Submit only once.  This may take several seconds to run.") . "</p>",
  );
  
  return $form;
  
}


function sample_data_install_form_validate($form, $form_state) {
  if ($form_state["values"]["passcode"] != "YES") {
    form_error("passcode", t("You did not enter YES into the box.  No data has been loaded."));
    return;
  }
}

/**
 * Actually perform the installation of data.
 */
function sample_data_install_form_submit($form, $form_state) {
  $file = fp_get_module_path("sample_data", TRUE, FALSE) . "/sample_data.sql";
  $sql = file_get_contents($file);
  
  // Okay, now we simply execute the contents of $sql, and we're good to go!
  // We need to split up the sql file into lines.
  $lines = explode("\n", $sql);
  foreach ($lines as $line) {
    $line = trim($line);
    // Does it start with TRUNCATE or INSERT?
    if (strstr($line, "INSERT") || strstr($line, "TRUNCATE") || strstr($line, "DELETE")) {
      db_query($line);
    }
  }
  
  // Clear our cache
  fp_clear_cache(); 
     
  fp_add_message(t("Sample data has been loaded into the database!  You now have a sample student
                    (named Sample Student), as well as a few ACCT courses and an ACCT degree, saved
                    in the 2012-2013 catalog year.  Also, some of your settings have been adjusted.
                    From the Main tab, you can search for the student by name to load their degree plan.
                    "));
}



